#include "HtmlHeader.hpp"

const QString HtmlHeader = QStringLiteral("<!DOCTYPE HTML PUBLI"
										  "C \"-//W3C//DTD HTML"
										  " 4.0//EN\" \"http://"
										  "www.w3.org/TR/REC-ht"
										  "ml40/strict.dtd\">\r"
										  "\n"
										  "<html><head><meta na"
										  "me=\"qrichtext\" con"
										  "tent=\"1\" /><meta c"
										  "harset=\"utf-8\" /><"
										  "style type=\"text/cs"
										  "s\">\r\n"
										  "p, li { white-space:"
										  " pre-wrap; }\r\n"
										  "</style></head><body"
										  " style=\" font-famil"
										  "y:\'Sans Serif\'; fo"
										  "nt-size:9pt; font-we"
										  "ight:400; font-style"
										  ":normal;\">");
const QString HtmlFooter = QStringLiteral("</body></html>");
const QString UnnecessaryFormatting = QStringLiteral("style=\" margin-top:"
													 "6px; margin-bottom:6"
													 "px; margin-left:0px;"
													 " margin-right:0px; -"
													 "qt-block-indent:0; t"
													 "ext-indent:0px;\"");
